In [1]:
#pip install tensorflow

A tensorflow workflow


Get the data ready

*   List item
*   List item



Build or pick a pretrained model

Fit the model to the data to make a prediction

Evaluate the model

Improve through experimentation

Save and reload your trained model.

In [2]:
import tensorflow as tf

In [3]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number o dimensions of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.,],
                              [14., 2.],
                              [5., 5.],
                              [1., 5.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[10.,  7.],
       [14.,  2.],
       [ 5.,  5.],
       [ 1.,  5.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [5, 6, 7]],
                      [[7, 5, 2],
                       [9, 7, 1]],
                      [[9, 1, 4],
                       [4, 3, 8]]], dtype = tf.int32)

In [12]:
tensor.ndim

3

Creating a Variable

[link text](https://)

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
# Create a variable
changeable_tensor = tf.Variable([10, 7])
unchanageable_tensor = tf.constant([10, 7])
changeable_tensor, unchanageable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
unchanageable_tensor[0].assign(7)
unchanageable_tensor

AttributeError: ignored

### Creating random tensors


In [18]:
# Create two random and the same tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape= (3, 2))

In [19]:
# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of a tensor

In [20]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
#shuffle our not_shuffled tensor
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, 42) #operation random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise:** Read through tensorflow documentation on random seed and practice 5 random tensors

Both operation and global level random seed must be set to make reproducible experiments.

In [21]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

## Other ways to make tensors

In [22]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# Create a tensor of all zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

The main difference between Numpy Arrays and Tensors is that Tensors can be run on gpu for faster computation

In [24]:
# Convert numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
A = tf.constant(numpy_A, shape= (2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape= (3, 8))
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [26]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

3
1
2


###Getting Information from Tensors

* Shape
* Rank
* Size
* Axis

In [27]:
# Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [29]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimensio from each index except for the final one
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [31]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [32]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [34]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [35]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
rank_3_tensor.ndim

3

In [37]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors
**Basic operations**
+*/-

In [39]:
tensor = tf.constant([[10, 8], [15, 6]])
tensor + 15

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 23],
       [30, 21]], dtype=int32)>

In [40]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [15,  6]], dtype=int32)>

In [41]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  80],
       [150,  60]], dtype=int32)>

In [42]:
# Subtraction
tensor - 50

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-40, -42],
       [-35, -44]], dtype=int32)>

In [43]:
# TensorFlow built-in multiply
tf.multiply(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 32],
       [60, 24]], dtype=int32)>

### Matrix Multiplication

This is one of the most common machine learning operation

In [44]:
# Matrix Multiplication

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 128],
       [240, 156]], dtype=int32)>

In [45]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  64],
       [225,  36]], dtype=int32)>

In [46]:
tensor_a = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
tensor_b = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])

tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [47]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 128],
       [240, 156]], dtype=int32)>

In [48]:
tensor.shape

TensorShape([2, 2])

In [49]:
X = tf.constant([[1, 2],
                 [4, 5],
                 [10, 6]])
Y = tf.constant([[1, 2, 3, 0],
                 [4, 5, 6, 4],
                 [4, 0, 1, 6]])

In [52]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [53]:
X.shape, tf.reshape(Y, shape= (3, 4))

(TensorShape([3, 2]), <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[1, 2, 3, 0],
        [4, 5, 6, 4],
        [4, 0, 1, 6]], dtype=int32)>)

In [54]:
# Let's change the shape of Y
tf.reshape(Y, shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 0],
       [4, 5, 6, 4],
       [4, 0, 1, 6]], dtype=int32)>

In [55]:
tf.reshape(X, shape= (2, 3)) @ tf.reshape(Y, shape= (3, 4))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[25, 12, 19, 32],
       [69, 60, 81, 76]], dtype=int32)>

In [56]:
tf.matmul(tf.reshape(Y, shape=(4, 3)), tf.reshape(X, shape=(3, 2)))

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[39, 30],
       [66, 50],
       [62, 56],
       [64, 41]], dtype=int32)>

In [57]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4, 10],
       [ 2,  5,  6]], dtype=int32)>

In [58]:
# Matrix multiplication with transpose
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[57, 22, 37, 76],
       [46, 29, 42, 56]], dtype=int32)>

** The dot product **
You can perform matrix multiplication using:
- tf.matmul()
- tf.tensordot()

In [59]:
# Compute the dot product of X and Y
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[57, 22, 37, 76],
       [46, 29, 42, 56]], dtype=int32)>

In [60]:
# Perform matrix multiplication
tf.matmul(X, tf.reshape(Y, shape= (2, 6)))

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[13, 10, 11,  0,  6, 17],
       [34, 28, 32,  0, 21, 50],
       [46, 44, 54,  0, 46, 86]], dtype=int32)>

In [61]:
# Check the values of Y, reshaped Y and transpose Y
print("Normal Y:", Y)
print("Reshaped Y: ",tf.reshape(Y, shape=(4, 3)))
print("Transposed Y:", tf.transpose(Y))

Normal Y: tf.Tensor(
[[1 2 3 0]
 [4 5 6 4]
 [4 0 1 6]], shape=(3, 4), dtype=int32)
Reshaped Y:  tf.Tensor(
[[1 2 3]
 [0 4 5]
 [6 4 4]
 [0 1 6]], shape=(4, 3), dtype=int32)
Transposed Y: tf.Tensor(
[[1 4 4]
 [2 5 0]
 [3 6 1]
 [0 4 6]], shape=(4, 3), dtype=int32)


Change the datatype of a tensor

In [62]:
B = tf.constant([1.7, 7.5])
B.dtype

tf.float32

In [63]:
C = tf.constant([1, 8])
C.dtype

tf.int32

In [64]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.5], dtype=float16)>,
 tf.float16)

In [65]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 8.], dtype=float32)>

### Aggregating Tensors

Condensing tensors from multiple values to smaller values

In [66]:
# Get absolute values
D = tf.constant([-9, 5])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-9,  5], dtype=int32)>

In [67]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 5], dtype=int32)>

Other forms of aggreagation

- Minimum
- Maximum
- Mean 
- Sum

In [68]:
F = tf.constant(np.random.randint(0, 100, size= 50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17, 26, 50, 43, 75, 65, 39, 85, 27, 98, 97, 64, 94, 97, 43, 49, 16,
       51, 39, 27, 35, 38, 11, 56, 16, 98, 17, 91, 51, 66, 70, 48, 69, 93,
       93, 45, 66, 16, 67, 19, 22, 64, 23, 30, 74,  1,  4, 19, 93, 92])>

In [69]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [70]:
# Minimum
min = tf.reduce_min(F)
min

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [71]:
# Maximum
max = tf.reduce_max(F)
max

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [72]:
# Mean
mean = tf.reduce_mean(F)
mean

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [73]:
# Sum
sum = tf.reduce_sum(F)
sum

<tf.Tensor: shape=(), dtype=int64, numpy=2589>

In [74]:
# Find the variance and SD of Tensor F.
variance = tf.reduce_sum(tf.math.square((F - mean))) / (len(F))
variance

<tf.Tensor: shape=(), dtype=float64, numpy=847.22>

In [75]:
SD = tf.math.sqrt(variance)
SD

<tf.Tensor: shape=(), dtype=float64, numpy=29.107043821040982>

In [76]:
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=847>

In [77]:
tf.math.reduce_std(tf.cast(F,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.096592>

In [78]:
# Find the variance of our F tensor
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=846.61163>

# Find the positional maximum and Minimum of a tensor

In [79]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [80]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [81]:
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [82]:
F[tf.argmax(F)] == tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [83]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [84]:
# Find the positional minimum 
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [85]:
F[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=int64, numpy=16>

# Squeezing a tensor (removing all single dimensions)

In [86]:
# Create a tensor 
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape= [50]), shape= (1, 1, 1, 1, 50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [87]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [88]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

##One-hot Encoding

In [89]:
# Create a list of indices
some_list = [0, 1, 2, 3]
depth = 4

tf.one_hot(some_list, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth, on_value = "yo, I love deep learning", off_value = "I love to sing")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo, I love deep learning', b'I love to sing',
        b'I love to sing', b'I love to sing'],
       [b'I love to sing', b'yo, I love deep learning',
        b'I love to sing', b'I love to sing'],
       [b'I love to sing', b'I love to sing',
        b'yo, I love deep learning', b'I love to sing'],
       [b'I love to sing', b'I love to sing', b'I love to sing',
        b'yo, I love deep learning']], dtype=object)>

In [91]:
## Squaring, log, square root
I = tf.range(1, 10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
# Square it
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [93]:
# Find the square root

tf.sqrt(tf.cast(I, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [94]:
tf.math.log(tf.cast(I, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [95]:
# Round up values 
J = tf.math.log(tf.cast(I, dtype=tf.float32))
tf.round(J)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([0., 1., 1., 1., 2., 2., 2., 2., 2.], dtype=float32)>

In [96]:
# Sigmoid function

tf.sigmoid(J)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.5       , 0.6666666 , 0.75      , 0.8       , 0.8333334 ,
       0.85714287, 0.875     , 0.88888884, 0.90000004], dtype=float32)>

In [97]:
# Calculate the reciprocal values
tf.math.reciprocal(J)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([       inf, 1.442695  , 0.9102392 , 0.7213475 , 0.6213349 ,
       0.5581106 , 0.5138983 , 0.48089835, 0.4551196 ], dtype=float32)>

### Tensor and Numpy

In [98]:
K = tf.constant(np.array([12., 5., 1.]))
K

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([12.,  5.,  1.])>

In [99]:
np.array(K), type(np.array(K))

(array([12.,  5.,  1.]), numpy.ndarray)

In [100]:
# Convert Tensor to NumPy array
K.numpy(), type(K.numpy())

(array([12.,  5.,  1.]), numpy.ndarray)

In [101]:
K = tf.constant([4.])
K.numpy()[0]

4.0

In [102]:
numpy_K = tf.constant(np.array([4., 5., 2.]))
tensor_K = tf.constant([4., 5., 2.])

# Check the datatypes of each
numpy_K.dtype, tensor_K.dtype

(tf.float64, tf.float32)